### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by rachitm12** [zynga/rl-bakery#11]
Hi! I keep getting this runtime error. every time i try to run the example.

**Comment by patrick-halina** [comment]
Can you provide us the full stack? We can't reproduce the error on our end. Also, which version of Python are you using?

**Comment by rachitm12** [comment]
> Can you provide us the full stack? We can't reproduce the error on our end. Also, which version of Python are you using?

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/rachitmishra/rl-bakery/rl_bakery/example/cartpole.py", line 3, in <module>
    from rl_bakery.applications.tfenv.tf_env_engine_conf import TFEnvEngineConfig
  File "/Users/rachitmishra/rl-bakery/rl_bakery/applications/tfenv/tf_env_engine_conf.py", line 1, in <module>
    from rl_bakery.engine.abstract_engine_config import AbstractEngineConfig
  File "/Users/rachitmishra/rl-bakery/rl_bakery/engine/abstract_engine_config.py", line 2, in <module>
    from rl_bakery.data_manager.data_manager import DataManager, DATANAME, InMemoryStorage, TFAgentStorage
  File "/Users/rachitmishra/rl-bakery/rl_bakery/data_manager/data_manager.py", line 3, in <module>
    from tf_agents.agents.tf_agent import TFAgent
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tf_agents/__init__.py", line 66, in <module>
    _ensure_tf_install()
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tf_agents/__init__.py", line 37, in _ensure_tf_install
    import tensorflow as tf
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 959, in _find_and_load_unlocked
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tensorflow_core/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 84, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 4756, in <module>
    _escapedPunc = Word( _bslash, r"\[]-*.$+^?()~ ", exact=2 ).setParseAction(lambda s,l,t:t[0][1])
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1284, in setParseAction
    self.parseAction = list(map(_trim_arity, list(fns)))
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1066, in _trim_arity
    this_line = extract_stack(limit=2)[-1]
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1050, in extract_stack
    frame_summary = traceback.extract_stack(limit=-offset+limit-1)[offset]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 363, in extract
    f.line
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 48, in getlines
    for mod in sys.modules.values():
RuntimeError: dictionary changed size during iteration
(venv) MacBook-Pro:rl-bakery rachitmishra$ xport JAVA_HOME=/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home sudo gedit~/.bash_profile
-bash: xport: command not found
(venv) MacBook-Pro:rl-bakery rachitmishra$ export JAVA_HOME=/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home sudo gedit~/.bash_profile
-bash: export: `gedit~/.bash_profile': not a valid identifier
(venv) MacBook-Pro:rl-bakery rachitmishra$ export JAVA_HOME=/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
(venv) MacBook-Pro:rl-bakery rachitmishra$ python3 -m rl_bakery.example.cartpole
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/rachitmishra/rl-bakery/rl_bakery/example/cartpole.py", line 3, in <module>
    from rl_bakery.applications.tfenv.tf_env_engine_conf import TFEnvEngineConfig
  File "/Users/rachitmishra/rl-bakery/rl_bakery/applications/tfenv/tf_env_engine_conf.py", line 1, in <module>
    from rl_bakery.engine.abstract_engine_config import AbstractEngineConfig
  File "/Users/rachitmishra/rl-bakery/rl_bakery/engine/abstract_engine_config.py", line 2, in <module>
    from rl_bakery.data_manager.data_manager import DataManager, DATANAME, InMemoryStorage, TFAgentStorage
  File "/Users/rachitmishra/rl-bakery/rl_bakery/data_manager/data_manager.py", line 3, in <module>
    from tf_agents.agents.tf_agent import TFAgent
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tf_agents/__init__.py", line 66, in <module>
    _ensure_tf_install()
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tf_agents/__init__.py", line 37, in _ensure_tf_install
    import tensorflow as tf
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 959, in _find_and_load_unlocked
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tensorflow_core/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 84, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 4756, in <module>
    _escapedPunc = Word( _bslash, r"\[]-*.$+^?()~ ", exact=2 ).setParseAction(lambda s,l,t:t[0][1])
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1284, in setParseAction
    self.parseAction = list(map(_trim_arity, list(fns)))
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1066, in _trim_arity
    this_line = extract_stack(limit=2)[-1]
  File "/Users/rachitmishra/rl-bakery/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1050, in extract_stack
    frame_summary = traceback.extract_stack(limit=-offset+limit-1)[offset]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 363, in extract
    f.line
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 48, in getlines
    for mod in sys.modules.values():
RuntimeError: dictionary changed size during iteration

**Comment by patrick-halina** [comment]
It looks like this is an issue with Tensorflow installations on Mac: https://github.com/tensorflow/tensorflow/issues/33183

A lot of people suggest upgrading to Python 3.7.5, that's what I'm using and I'm not seeing that issue.

**Comment by rachitm12** [comment]
Thank you so much!! that worked
